kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mongo-dmp
  namespace: default
  labels:
    app: mongodb
spec:
  storageClassName: release
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi