
image: traefik
# imageTag: alpine # Alpine only needed for debug and ssh access
debug:
    enabled: true
accessLogs:
    enabled: false
    filePath: /var/log/traefik.log
rbac:
    enabled: true 
ssl: 
    enabled: true 
    enforced: false
service:
    annotations: 
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"