mongodb:
    enabled: true
    mongodbRootPassword: <root password>
    mongodbUsername: tctsyadmin
    mongodbPassword: <mongodb password>
    mongodbDatabase: rocketchat
    replicaSet:
        enabled: true
        replicas:
            secondary: 1
            arbiter: 1
        pdb:
            minAvailable:
                secondary: 1
                arbiter: 1
image:
    #tag:  2.4.11 # we will fill this out with our downgraded version
    imagePullPolicy: Always
replicaCount: 1
ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: 'traefik'
host: tctsy.chat