mongodb:
    enabled: true
    mongodbRootPassword: <your root password>
    mongodbUsername: tctsyadmin
    mongodbPassword: <yourmongodb password>
    mongodbDatabase: rocketchat
    replicaSet:
        enabled: true
        replicas:
            secondary: 1
            arbiter: 1
        pdb:
            minAvailable:
                secondary: 1
                arbiter: 1
image:
    tag:  2.4.11 # we will fill this out with our downgraded version
    imagePullPolicy: Always
ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: 'traefik'
    tls:
        - secretName: rc-tls
          hosts:
              - flostest.online
livenessProbe:
    enabled: false
readinessProbe:
    enabled: false
host: flostest.online